variables:
  azureSubscription: '058a85c1-7f83-408d-baae-f0719efbd86b'
  AZURE_SUB: $(azureSub)
  resourceGroupName: 'rg-devopsspike-dev-001'
  location: 'eastus'
  armTemplateUrl: 'https://raw.githubusercontent.com/chrisjensenuk/DevOpsSpike/master/azuredeploy.json'

stages:
- stage: CreateEnv
  displayName: Create Environment
  jobs:
  - job: CreateEnv
    displayName: Create Environment
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: $(AZURE_SUB)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'URL of the file'
        csmFileLink: $(armTemplateUrl)
        deploymentMode: 'Complete'

- template: azure-pipelines-template-ci-cd.yml