pr:
- master

variables:
  # Agent VM image name
  vmImageName: 'vs2017-win2016'

stages:
- stage: Build
  displayName: Build & Test stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - template: azure-pipelines-template-build.yml